from enum import StrEnum


class ErrorCode(StrEnum):
    TENANT_NOT_FOUND = "TENANT_NOT_FOUND"
    TENANT_CREATE_REQUEST_INVALID = "TENANT_CREATE_REQUEST_INVALID"
    TENANT_CHANNEL_NOT_SUPPORTED = "TENANT_CHANNEL_NOT_SUPPORTED"
    MISSING_ENV_KEY = "MISSING_ENV_KEY"
    DOCKER_NOT_RUNNING = "DOCKER_NOT_RUNNING"
    CONTAINER_START_FAILED = "CONTAINER_START_FAILED"
    HEALTHCHECK_TIMEOUT = "HEALTHCHECK_TIMEOUT"
    TRAEFIK_ROUTER_NOT_READY = "TRAEFIK_ROUTER_NOT_READY"
    NETWORK_NOT_FOUND = "NETWORK_NOT_FOUND"
    CONFIG_FILE_NOT_FOUND = "CONFIG_FILE_NOT_FOUND"
    PLATFORM_CONFIG_MISSING = "PLATFORM_CONFIG_MISSING"
    LLM_BUDGET_EXHAUSTED = "LLM_BUDGET_EXHAUSTED"
    BACKUP_FILE_NOT_FOUND = "BACKUP_FILE_NOT_FOUND"
    BACKUP_FORMAT_INVALID = "BACKUP_FORMAT_INVALID"


class WarningCode(StrEnum):
    TENANT_ALREADY_EXISTS = "TENANT_ALREADY_EXISTS"
    TENANT_ALREADY_RUNNING = "TENANT_ALREADY_RUNNING"
    TENANT_ALREADY_STOPPED = "TENANT_ALREADY_STOPPED"
