from enum import StrEnum


class ErrorCode(StrEnum):
    TENANT_NOT_FOUND = "TENANT_NOT_FOUND"
    TENANT_CREATE_REQUEST_INVALID = "TENANT_CREATE_REQUEST_INVALID"
    TENANT_DELETE_REQUEST_INVALID = "TENANT_DELETE_REQUEST_INVALID"
    TENANT_CHANNEL_NOT_SUPPORTED = "TENANT_CHANNEL_NOT_SUPPORTED"
    TENANT_STATUS_INVALID = "TENANT_STATUS_INVALID"
    MISSING_ENV_KEY = "MISSING_ENV_KEY"
    DOCKER_NOT_RUNNING = "DOCKER_NOT_RUNNING"
    CONTAINER_START_FAILED = "CONTAINER_START_FAILED"
    CONTAINER_STOP_FAILED = "CONTAINER_STOP_FAILED"
    HEALTHCHECK_TIMEOUT = "HEALTHCHECK_TIMEOUT"
    TRAEFIK_ROUTER_NOT_READY = "TRAEFIK_ROUTER_NOT_READY"
    TRAEFIK_ROUTER_NOT_REMOVED = "TRAEFIK_ROUTER_NOT_REMOVED"
    NETWORK_NOT_FOUND = "NETWORK_NOT_FOUND"
    CONFIG_FILE_NOT_FOUND = "CONFIG_FILE_NOT_FOUND"
    PLATFORM_CONFIG_MISSING = "PLATFORM_CONFIG_MISSING"
    LLM_BUDGET_EXHAUSTED = "LLM_BUDGET_EXHAUSTED"
    WALLET_REQUEST_INVALID = "WALLET_REQUEST_INVALID"
    USER_BALANCE_NOT_FOUND = "USER_BALANCE_NOT_FOUND"
    LITELLM_KEY_ISSUE_FAILED = "LITELLM_KEY_ISSUE_FAILED"
    LITELLM_KEY_REVOKE_FAILED = "LITELLM_KEY_REVOKE_FAILED"
    BACKUP_FILE_NOT_FOUND = "BACKUP_FILE_NOT_FOUND"
    BACKUP_FORMAT_INVALID = "BACKUP_FORMAT_INVALID"


class WarningCode(StrEnum):
    TENANT_ALREADY_EXISTS = "TENANT_ALREADY_EXISTS"
    TENANT_ALREADY_RUNNING = "TENANT_ALREADY_RUNNING"
    TENANT_ALREADY_STOPPED = "TENANT_ALREADY_STOPPED"
